CreateDnsDelegation = "false"
DatabasePath = "C:\\Windows\\NTDS"
DomainMode = "WinThreshold"
DomainName = "lab.local"
DomainNetbiosName = "lab"
ForestMode = "WinThreshold"
InstallDns = "true"
LogPath = "C:\\Windows\\NTDS"
NoRebootOnCompletion = "true"
SafeModeAdministratorPassword = "P@ssw0rd12344321!"
SysvolPath = "C:\\Windows\\SYSVOL"
Force = "true"